#!/usr/bin/env bash

(cd ../../local && make -j8 DIM=2 USE_EB=FALSE AMREX_PARTICLES=TRUE)

EXE=MFP.2d.gnu.MPI.PARTICLES.ex

python3 make_particles_file.py

INPUTS=*.inputs

rm -r *plt* *chk* mov

mpirun -n 8 ../../local/${EXE} ${INPUTS} 2>&1 | tee run_log.txt

../visit.sh .

python3 movie.py
python3 check.py

