#!/usr/bin/env bash

(cd ../../local && make -j8 DIM=2 USE_EB=FALSE AMREX_PARTICLES=FALSE)

EXE=../../local/MFP.2d.gnu.MPI.ex

INPUTS=*.inputs

rm -r *plt* *chk*

mpirun -n 8 ${EXE} ${INPUTS} 2>&1 | tee run_log.txt

python3 plot.py
