#!/usr/bin/env bash

(cd ../../local && make -j8 DIM=2 EILMER_GAS=TRUE)
EXE=../../local/MFP.2d.gnu.MPI.EILMER.ex

INPUTS=*.inputs

rm -r *plt* *chk*

sh prep-chem.sh

mpirun -n 1 ${EXE} ${INPUTS} 2>&1 | tee run_log.txt

../visit.sh .

python3 plot.py
