#!/usr/bin/env bash

(cd ../../../ && make EILMER_GAS=TRUE EILMER_INSTALL_LIB=TRUE)

EXE=../../../MFP.2d.gnu.MPI.EB.PARTICLES.EILMER.ex

INPUTS=*.inputs

rm -r *plt* *chk*

source ../../../env

sh prep-chem.sh

mpirun -n 1 ${EXE} ${INPUTS} 2>&1 | tee run_log.txt

../visit.sh .

# python script is a bit buggy right now and needs to be fixed
# python3 plot.py
