#!/usr/bin/env bash

(cd ../../local && make -j8 DIM=2 USE_EB=FALSE AMREX_PARTICLES=TRUE)

EXE=../../local/MFP.2d.gnu.MPI.PARTICLES.ex

INPUTS=BTRMI.inputs

rm -r *chk* *plt*
rm -r mov

python3 make_particles_file.py

mpirun -n 8 ${EXE} ${INPUTS} 2>&1 | tee run_log.txt

../visit.sh .

python3 ../Thermal-RMI/plot.py
python3 ../Thermal-RMI/movie.py
