# Running this makefile will build cerberus in this directory instead
# of the root directory
# any Make.local in this directory will always take priority over the
# global "Make.local" in the root of the cerberus repo

all:
	$(MAKE) -f ../../Makefile

