#!/usr/bin/env bash

(cd ../../local && make -j8 DIM=1 USE_EB=FALSE AMREX_PARTICLES=FALSE)

EXE=../../local/MFP.1d.gnu.MPI.ex
rm -r *plt* *chk*
INPUTS=*.inputs
mpirun -n 1 ${EXE} ${INPUTS} 2>&1 | tee run_log.txt

python3 check.py
