#!/usr/bin/env bash

DATE_WITH_TIME=`date "+%Y%m%d-%H%M%S"`


(cd ../../../ && make -j8)

EXE=../../../MFP.2d.gnu.MPI.EB.PARTICLES.ex

INPUTS=*.inputs

rm -r *plt* *chk* mov

mpirun ${EXE} ${INPUTS} 2>&1 | tee run_log_${DATE_WITH_TIME}.txt

../visit.sh .

# python scripts are a bit buggy at the moment, need fixing!
# python3 plot.py
# python3 movie.py
