#!/usr/bin/env bash

# USE_PRIM_FLOOR=TRUE is the default; stated explicitly because this test
# relies on the density/pressure floor layers (see problem_definition.lua)
(cd ../../local && make -j8 DIM=3 USE_EB=FALSE AMREX_PARTICLES=FALSE USE_PRIM_FLOOR=TRUE)

EXE=../../local/MFP.3d.gnu.MPI.ex

INPUTS=*.inputs

rm -rf plt* chk*

mpirun -n 10 ${EXE} ${INPUTS} 2>&1 | tee run_log.txt

python3 check.py
